feat: Allow server to return VersionNotSupported (#422)
The pull and push endpoints can now return VersionNotSupportedResponse
which has the type:

```ts
type VersionNotSupportedResponse = {
  error: 'VersionNotSupported';
  versionType?: 'pull' | 'push' | 'schema' | undefined;
};
```

The `versionType` is optional for now to allow more adhoc responses.

When the server returns this we call onUpdateNeeded which will reload by
default.

We allow these responses in both DD31 and SDD. The reason to also
support them in SDD is to allow dealing with these in mutation recovery. For
SDD we end up deleting the client if its version is no longer supported.

If we get an error response recovering a DD31 client group we disable the
client group.

Towards #165