fix: make uuid creation for hashing lazy to avoid cf error (#505)
This needs to be lazy because the cloudflare worker environment will
throw an error if crypto.randomUUID is used statically.  Specifically:
```
Error: Some functionality, such as asynchronous I/O, timeouts, and
generating random values, can only be performed while handling a
request.
```

Also delete tar package that was accidentally checked in.