fix(zql): fix overlay logic for edit (#3009)
Without this fix edits are not correctly overlayed during push.

The new "fetch during push edit change" failed without this fix, like this:

```
  expect(fetchDuringPush).toEqual([
    {
      row: {a: 'a', b: 'b2', c: 'c2'},
      relationships: {},
    },
  ]);

 FAIL  src/ivm/memory-source.test.ts > fetch during push edit change
AssertionError: expected [ { …(2) } ] to deeply equal [ { …(2) } ]

- Expected
+ Received

  Array [
    Object {
      "relationships": Object {},
      "row": Object {
        "a": "a",
-       "b": "b2",
-       "c": "c2",
+       "b": "b",
+       "c": "c",
      },
    },
  ]
```